runtime: nodejs
env: flex
service: eureka-stalker
env_variables:
  EUREKA_ENV: dev
beta_settings:
  cloud_sql_instances: dotted-vim-164110:us-east1:eureka-dev

# Instance resources size
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
# Disable auto-scale
manual_scaling:
  instances: 1
# Disable health checks
health_check:
  enable_health_check: False
